# Generated by Django 4.2.16 on 2024-09-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('isHappy', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageSrc',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://loremflickr.com/200/200?random=7', max_length=256),
        ),
    ]
